version: "3"

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel}
      - MYSQL_ROOT_PASSWORD=${DB_PASS_ROOT:-password}
    volumes:
      - ./logs/db:/var/log/mysql
      - db:/var/lib/mysql
    ports:
      - ${DB_PORT_TOOL:-3306}:3306
    restart: always

  app:
    build:
      context: ./docker/php/
    volumes:
      - ${SOURCE:-./}:/var/www/html
      - ./logs/app:/var/log/php
    working_dir: /var/www/html
    restart: always

  web:
    image: nginx:alpine3.18
    depends_on:
      - app
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - ${SOURCE:-./}/public:/var/www/html/public
      - ./logs/nginx:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

volumes:
  db: